home/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout


urlpatterns = [
    url(r'^$', login, {'template_name':'home/welcome.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^home/comments/$', views.PostView.as_view(), name='comments'),
    url(r'^home/rsvp/$', views.ReceptionView.as_view(), name='reception'),
    # url(r'^register/$', views.register, name='register'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

if settings.DEBUG:
    import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

home/models.py
from django.db import models
from .choices import choice,plusOnes
from django.contrib.auth.models import User
from django.utils import timezone

class UserFullName(User):
    class Meta:
        proxy=True
        verbose_name= 'Guest RSVP'
        verbose_name_plural = 'Guests RSVPs'

    def __str__(self):
        return self.get_full_name()

class RSVP(models.Model):
    user = models.ForeignKey(UserFullName, on_delete=models.CASCADE)
    reception = models.CharField(max_length=20,choices=choice,default='No Response')
    extra = models.CharField(max_length=10,choices=plusOnes,default=0)  

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class Post(models.Model):
    user = models.ForeignKey(UserFullName, on_delete='cascade')
    post = models.CharField(max_length=300)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.post

home/forms.py
from django import forms
from .models import RSVP, Post
from .choices import choice, plusOnes


class PostForm(forms.ModelForm):
    post = forms.CharField(widget=forms.Textarea, label='Post')

    class Meta:
        model = Post
        fields = ('post',)


class ReceptionForm(forms.ModelForm):
    receptions = forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            choices=choice,
            required=True,
            initial='No Response',
    )

    class Meta:
        model = RSVP
        fields =('reception',)

class ExtrasForm(forms.ModelForm):
    extras = forms.MultipleChoiceField(
            widget=forms.CheckboxSelectMultiple,
            choices=plusOnes,
            required=True,
            initial='0',
    )

    class Meta:
        model = RSVP
        fields =('extra',)

home/views.py
# from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView, FormView
from django.shortcuts import render, redirect
from .forms import PostForm, ReceptionForm, ExtrasForm
from .models import RSVP, Post
from django import forms
from django.contrib.auth.decorators import login_required

# --------------- Home / GET View ---------------------

class HomeView(TemplateView):
    template_name = 'home/content.html'

    def get(self,request,*args, **kwargs):
        if request.user.is_active:
            receptionform = ReceptionForm(self.request.GET or None)
            extrasform = ExtrasForm(self.request.GET or None)
            rsvps = RSVP.objects.filter(user=request.user)
            postform = PostForm(self.request.GET or None)
            posts = Post.objects.all().order_by('-date')

            args = {
                    'receptionform': receptionform, 
                    'extrasform': extrasform, 
                    'rsvps':rsvps,
                    'postform':postform, 'posts':posts
            }
            return render(request, self.template_name, args)

        else:
            posts = Post.objects.all().order_by('-date')
            return render(request, self.template_name, {'posts':posts})

# ------------------ POST / Update Views ---------------------------------

class ReceptionView(FormView):
    template_name = 'home/rsvp.html'

    def post(self, request):
        if request.method == 'POST':

            if len(RSVP.objects.filter(user=request.user)) == 0:
                form1 = ReceptionForm(request.POST)
                if form1.is_valid():
                    post = form1.save(commit=False) 
                    post.user = request.user
                    post.save()

                    guest = RSVP.objects.get(user=request.user)
                    form2 = ExtrasForm(data=request.POST, instance=guest)
                    if form2.is_valid():
                        post = form2.save(commit=False)
                        post.save()
                        return redirect('/home/#rsvp')

            else:
                guest = RSVP.objects.get(user=request.user)
                form1 = ReceptionForm(data=request.POST, instance=guest)
                form2 = ExtrasForm(data=request.POST, instance=guest)
                if form1.is_valid() or form2.is_valid():
                    post1 = form1.save(commit=False)
                    post2 = form2.save(commit=False)
                    post1.save()
                    post2.save()
                    return redirect('/home/#rsvp')
        else:
            form1 = ReceptionForm()
            form2 = ExtrasForm()

        args = {'form1':form1,
                'form2':form2,
                }
        return render(request, self.template_name, args)


class PostView(FormView):
    template_name = 'home/comments.html'

    def post(self, request):
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            text = form.cleaned_data['post']
            form = PostForm()
            return redirect('/home/#comments')

        args = {'form':form, 'text':text}
        return render(request, self.template_name, args)


# def register(request):
#     if request.method =='POST':
#         form = UserCreationForm(request.POST)
#         if form.is_valid:
#             form.save()
#             return redirect('/home')
#     else:
#         form = UserCreationForm()
# 
#         args = {'form':form}
#         return render(request, 'home/register.html', args)

home/templates/base.html
<!DOCTYPE>
<html lang='en'>

<head>
    <title>Welcome/ Home</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load staticfiles %}
    <!-- CSS -->
    <link rel="stylesheet" href='{% static "home/css/bootstrap.min.css" %}'>

    <link rel='stylesheet' href='{% static "home/css/personal.css" %}'>
    <!-- JS -->
    <script src={% static "home/js/jquery.js" %}></script>
    <script src='{% static "home/js/bootstrap.min.js" %}'></script>
    <script src={% static "home/js/personal.js" %}></script>
    <!--<script type="text/javascript" src="http://livejs.com/live.js"></script>-->
</head>

<body>

    {% block welcome %}{% endblock %}
    {% block content %}{% endblock %}
    {% block logout %}{% endblock %}

</body>
</html>

home/templates/home/carousel.html
{% block carousel %}
<div id="myCarousel" class="carousel" data-ride="carousel" data-pause="false" data-interval="3000">
  <div class="carousel-inner" role="listbox">
    <div class="item active">
        <img src="static/home/pics/wedsitePics/yourPic.jpg">
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg"> 
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg">
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg"> 
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg">
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg"> 
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg"> 
    </div>
    <div class="item">
        <img src="static/home/pics/wedsitePics/yourPic.jpg"> 
    </div>
</div>
{% endblock carousel %}

home/templates/home/comments.html
{% block comments %}

<a name="comments"></a>
<div class="commentSection">
    <h1>We would love to hear from you!</h1>
    <h6 style="color:white">
    Just a reminder, this site is open to everyone.<br>
    Please do not leave any personal information in the comment section.<br>
    Thank you!</h6>

<div id=formPost>
    {% if user.is_authenticated %}
    <form action="/home/comments/" method="post">
        {% csrf_token %}
        {{ postform.as_p }}
        <button type="submit" class="formBtn">Submit</button>
    {% else %}
        <h5 style="color:white;margin-top:2%;padding:1%;border-style:solid">
            You must be logged in to leave a comment.</h5>
    {% endif %}
        </form>
</div>

    {% for post in posts %}
    <h3 style="color:white;width:80%;margin-left:10%">{{ post.post|linebreaks }}</h3>
    <h6 style="color:grey">{{ post.user.get_full_name }} - {{ post.date }}</h6>
    <br>
    <hr style="width:30%">
    <br>
    {% endfor %}
</div>

{% endblock %}

home/templates/home/content.html
{% extends "base.html" %}
{% block content %}
{% include "home/header.html" %}
{% include "home/carousel.html" %}

<div class='content'>

<h1>We did it!</h1>
<h3 id="welcome">
    We've made this website to help get some of the information out pertaining to our
    special day.<br><br>
    Below you'll be able to RSVP to any events you might be involved with,
    find out what places we're registered with and enhance your knowledge of the parties
    involved!<br><br>
    If you're coming from out of town, we've also included a section with some information
    on some of the popular hotels in our area, as well as dining and things to see.<br>
    We hope you enjoy!
</h3>

{% include "home/rsvp.html" %}
{% include "home/party.html" %}
{% include "home/travel.html" %}
{% include "home/registry.html" %}
{% include "home/comments.html" %}

</div>

{% include "home/footer.html" %}
{% endblock %}

home/templates/home/footer.html
<footer>
    <a href="#top">Top of Page</a>
    <h4>Feel free to contact us with any questions, concerns or suggestions you may have.</h4>
    <h4>
        <div>
            <a href='mailto:#'>Email_1</a><br>
            <p>PhoneNumber_1</p>
        </div>
        <div>
            <a href='mailto:#'>Email_2</a><br>
            <p>PhoneNumber_2</p>
        </div>
    </h4>
</footer>

home/templates/home/header.html
<header>
    <div>
        {% if user.is_authenticated %}
            <a name="top"></a>
            <a href="#rsvp">RSVP</a>
            <a href="#party">Wedding Party</a>
            <a href="#travel">Travel Info</a>
            <a href="#registry">Registry</a>
            <a href="#comments">Comments</a>
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a style="margin-left:90%" href="{% url 'login' %}">Login</a>
        {% endif %}
        <h1>Welcome {{ request.user.first_name }}!</h1>
        <h1>Leonor Egoavil + Shane Wilson</h1>
        <h3>Saturday March 16th 2019</h3>
    </div>
</header>

home/templates/home/party.html
{% block party %}

<a name="party"></a>
<div class="party">
    <h1>Wedding Party</h1>
    <div>
        <h3>Parents of Bride</h3>
        <h4>Augusto Egoavil</h4>
        <h4>Laly Egoavil</h4>

        <h3>Brides Maides</h3>
        <h4>Anna Cristina Ojeda</h4>
        <h4>Elizabeth Myer</h4>
    </div>
    <div>
        <h3>Parents of Groom</h3>
        <h4>Dan Wilson</h4>
        <h4>Nannette Schmitt</h4>

        <h3>Groomsmen</h3>
        <h4>Aaron Brown</h4>
        <h4>Stephan Parkhurst</h4>
        <h4>James Jensen</h4>
    </div>
</div>

{% endblock %}

home/templates/home/register.html
{% extends "base.html" %}
{% block register %}

<div class="container">
    <form method="post"
        {% csrf_token %}
        {{ form.as_p }}
    <p><input type="submit" value="Continue &rarr;"></p>
    </form>
</div>

{% endblock %}

home/templates/home/registry.html
{% block registry %}

<a name="registry"></a>
<div class="registry">
    <h1>Registry Information</h1>
    <p>Your presence on our big day is more than enough.<br>
        However, if you're feeling in a giving mood, please visit the site below where
        you will find a list of things that will help to make our house a home and
        also allow us to think of you fondly from time to time.</p>
</div>

<div class="regPics">
    <a href="https://www.zola.com/registry/leonorandshane" target="_blank">
        <img src="static/home/pics/zola.png">
    </a>
</div>

{% endblock %}

home/templates/home/rsvp.html
{% block rsvp %}
<div class='rsvp'>
    <a name="rsvp"></a>
    <h1>RSVP</h1>
    <h3>If you have recieved an invitation to any of the following, you
        may respond through the subsequent links.</h3>
    <div>
        <h3>Reception</h3>
        <p>Saturday, March 16th, 2019 at 6pm</p>
        <button id="rsvp1" type="button">RSVP</button>
    </div>
</div>

<span id="popup1">
    <button id="close">X</button>
    {% if user.is_authenticated %}
    <p>Will you be attending the Saturday evening Reception Party?</p><br>

    <form action="/home/rsvp/" method="post">
        {% csrf_token %}
        {{ receptionform }}
        <p>How many others in your party?</p>
        {% csrf_token %}
        {{ extrasform }} 
        <button type="submit" class="rsvpSubmitBtn">Submit</button>
        <br>
        <br>
        <h3>Your RSVP:</h3>
        {% for rsvp in rsvps %}
        <p>Attending: {{ rsvp.get_reception_display }}</p>
        <p>Extra Guests: {{ rsvp.get_extra_display }}</p>
        {% endfor %}

    </form>

    {% else %}
        <h3>You must be logged in to RSVP</h3>
    {% endif %}
</span>

{% endblock %}

home/templates/home/travel.html
{% block travel %}

<a name="travel"></a>
<div class="accomodations">
    <h1>Travel and Accomodation</h1>
    <div>
        <h3>Book a Hotel</h3>
        <img src="static/home/pics/hotel.jpg">
        <button id="details1" type="button">View Details</button>
    </div>
    <div>
        <h3>Cocktail Party</h3>
        <img src="static/home/pics/cocktailParty.jpeg">
        <button id="details2" type="button">View Details</button>
    </div>
    <div>
        <h3>Popular Attractions</h3>
        <img src="static/home/pics/miami.jpg">
        <button id="details3" type="button">View Details</button>
    </div>
</div>

<span id="popup4" autofocus>
<button id="close">X</button>
    <h3>
        There are several good choices for quality and unique hotels in the South Florida
        area. I've comprised a little list of a few popular ones that you're welcome to
        book a room with. These are merely suggestions however.
    </h3>
    <img class="hotelImg" src="static/home/pics/marriott.jpg">
    <p>
        First on our list, we have the JW Marriott. Located in the heart
        of Brickell, there's no shortage of activities within walking distance.
        It is where the groom and bride will be staying. We have a block of rooms
        available starting at $279 per night. Contact Leo or myself if you would
        like more information or would like to join our party.
    </p>
    <a href="http://www.marriott.com/hotels/travel/miajw-jw-marriott-miami/">Website</a>
    | Reserve: 305-329-3500

    <img class="hotelImg" src="static/home/pics/biltmore.jpg">
    <p>
        Second, we have the historic Biltmore Hotel. Located in Coral Gables,
        this is the closest lodging between the ceremony and reception. The Biltmore 
        boasts the largest hotel pool in the United States and one of the finest golf 
        courses.
    </p>
    <a href="http://www.biltmorehotel.com/">Website</a>
    | Reserve: 855-311-6903

    <img class="hotelImg" src="static/home/pics/fontainebleau.jpg">
    <p>
        If you're looking to stay closer to the beach, another iconic hotel to consider
        is the Fontainebleau. Located right in South Beach, it's a popular hotel for
        tourists and beach-goers alike. The Fontainebleau also contains Club LIV, being
        named one of the hottest nightclubs in the city.
    </p>
    <a href="https://fontainebleau.com/">Website</a>
    | Reserve: 800-548-8886

    <img class="hotelImg" src="static/home/pics/east.jpg">
    <p>
        EAST is a hotel located downtown Miami in Brickell City Centre. Opening in 2016,
        EAST is branded as a luxary hotel with several restaurants and a rooftop bar.
    </p>
    <a href="http://www.east-miami.com/">Website</a>
    | Reserve: 305-712-7000

    <h3>Some Cheaper Options Close to the Party</h3>
    <br>

    <p>
        Leamington Hotel<br>
        <a href="http://www.leamingtonhotel.com/">Website</a>
        | Reserve: 305-373-7783
    </p><br>
    <p>
        Courtyard by Marriott Miami<br>
        <a href="http://www.marriott.com/hotels/travel/miadt-courtyard-miami-downtown-brickell-area/">Website</a>
        | Reserve: 305-374-3000
    </p><br>
    <p>
        River Park Hotel and Suites<br>
        <a href="http://riverparkmiami.com/">Website</a>
        | Reserve: 305-374-5100
    </p><br>
</span>

<span id="popup5" autofocus>
<button id="close">X</button>
    <h3>Bulla Gastrobar</h3>
    <img id="bullaImg" src="static/home/pics/bulla.png">
    <p>
        Our event is an adults only, black tie invited, evening cocktail party.<br><br>
        Bulla, pronounced {boo-yah}, is a Madrid inspired tapas bar, with a variety of
        entres ranging from smaller shared plates to larger paella dishes for the hungrier
        guest.<br>They also boast a nice selection of hand-crafted cocktails and an
        impressive wine list.<br>Ultimately, we feel like there is something here for
        everyone to enjoy.<br><br>If you're interested, feel free to check out the
        <a href="http://bullagastrobar.com/menus/coral-gables/" target="_blank">Menu</a>
        before hand!
    </p>
</span>

<span id="popup6" autofocus>
    <button id="close">X</button>
    <h3>Whether you're arriving early or staying later, we've comprised a short list of
        local attractions you may be interested in checking out!</h3><br><br>

    <img class="attractImg" src="static/home/pics/sobe.jpg">
    <p>
        South Beach<br>
        501-1699 Collins Ave Miami Beach, FL 33139<br>
        <a href="http://www.miamiandbeaches.com/places-to-see/
        south-beach-art-deco-district" target="_blank">More Info</a>
    </p>

    <img class="attractImg" src="static/home/pics/bayside.jpg">
    <p>
        Bayside Market Place<br>
        401 Biscayne Blvd, R106, Miami, FL 33132<br>
        305-577-3344 |
        <a href="http://www.baysidemarketplace.com/" target="_blank">Website</a>
    </p>

    <img class="attractImg" src="static/home/pics/walls.jpg">
    <p>
        Wynwood Walls<br>
        2520 NW 2nd Ave, Miami, FL 33127<br>
        305-531-4411 |
        <a href="http://www.thewynwoodwalls.com/" target="_blank">Website</a>
    </p>

    <img class="attractImg" src="static/home/pics/vizcaya.jpg">
    <p>
        Vizcaya Museum and Gardens<br>
        3251 S Miami Ave, Miami, Florida 33129<br>
        305-250-9133 |
        <a href="http://vizcaya.org/" target="_blank">Website</a>
    </p>

    <img class="attractImg" src="static/home/pics/seaquarium.JPG">
    <p>
        Miami Seaquarium<br>
        4400 Rickenbacker Causeway, Miami, FL 33149<br>
        (305) 361-5705 |
        <a href="https://www.miamiseaquarium.com/" target="_blank">Website</a>
    </p>

    <img class="attractImg" src="static/home/pics/jungle.jpg">
    <p>
        Jungle Island Adventure Park<br>
        1111 Parrot Jungle Trail, Miami, FL 33132<br>
        (305) 400-7000 |
        <a href="https://www.jungleisland.com/" target="_blank">Website</a>
    </p>
</span>

{% endblock %}

home/templates/home/welcome.html
{% extends "base.html" %}
{% block welcome %}

<header style="margin-bottom:5%">
    {% include "home/header.html" %}
</header>

<h3>
    If you wish to use site features such as RSVP and comments, please login.
</h3>
<header style="margin-bottom:3%;width:80%;margin-left:10%">
    <form id="loginForm" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="formBtn" type="submit">Login</button>
</header>
<h3 style="text-align:center">
    If you just want to browse the site for information, and do not plan<br>
    to use the online RSVP or comment section, please click<br>
    <a href="{% url 'home' %}">here</a></h3>
</h3>

{% endblock %}